from django.urls import path
from . import views

urlpatterns = [
    path("",views.index, name="index"),
    path("login/",views.loginUser, name="login"),
    path("login-user/", views.login_view,name="loginuser"),
    path("logout/", views.logout_page, name="logout"),
    path('signup/',views.signup, name='signup'),
    # path('get_presigned_url/<str:object_key>/', views.get_profile_picture_url, name='get_profile_picture_url'),
    path('search-user-book-query/',views.searchUserBookQuery, name='search-book'),
    path('available/',views.availableBooks, name='available'),
    path('newBooks/',views.newBooks,name='new-books'),
    path('issueBook/',views.issueBook, name='IssueBook'),
    path('issue-member-book/', views.addBookToMember, name='add-member-book'),  
    path('loan-records/',views.loanPageView, name='loan-view'),
    path('return-book/<int:loan_id>/',views.returnBookView, name='return-book-view'),
    path('pay-return-book/<int:loan_id>/', views.pay_return_book, name='pay-return-book'),
    path('view-notifications/', views.viewNotifications, name='notifications'),
    path('check-borrowed-book/',views.checkUserBooks, name='check-user-books'),
    path('author/',views.availableAuthors,name='author'),
    path('genre/',views.availableGenres,name='genre'),
    path('adminUI/',views.adminUI,name="adminUI"),
    path('search-book/',views.delete_book,name="search-book"),
    path('search-user/',views.delete_user,name="search-user"),
    path('add-book/',views.add_book,name="add-book"),
    path('add-user/',views.add_user,name="add-user"),
    path('get-user-details/', views.get_user_details, name='get_user_details'),
    path('update-user-details/', views.update_user_details, name='update_user_details'),
    path('adding-new-user/',views.addNewUser, name="adding-new-user"),
    path('list-of-books/', views.books_details, name="list-of-books"),
    path('get-auth-status/', views.get_authentication_status, name='get-auth-status'),
    path('view-books-admin/',views.viewBooksAdmin, name="view-books-admin"),
    path('view-users-admin/',views.viewUsersAdmin, name="view-users-admin"),
]