# Generated by Django 5.0.1 on 2024-02-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libxmApp', '0002_userprofile_user_photo_alter_loanmodel_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='libxmApp/media/'),
        ),
    ]
