# Generated by Django 5.0.1 on 2024-02-05 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libxmApp', '0003_alter_userprofile_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
