# Generated by Django 5.0.1 on 2024-02-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libxmApp', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
