# Generated by Django 5.0.1 on 2024-02-21 07:03

import libxmApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libxmApp', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, storage=libxmApp.models.S3MediaStorage(), upload_to=''),
        ),
    ]
